# Generated by Django 3.2.2 on 2021-05-12 20:34

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(verbose_name='First Name')),
                ('LastName', models.TextField(verbose_name='Last Name')),
                ('Email', django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='E-mail Addresses')),
                ('PhoneNumber', django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='Phone Number')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
