# Generated by Django 3.2.2 on 2021-05-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField(verbose_name='client_name')),
                ('email', models.TextField(unique=True, verbose_name='email')),
                ('passkey', models.TextField(verbose_name='passkey')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
